ROW_COUNT = 6
COLUMN_COUNT = 7
HIDDEN_LAYER_NEURON = ROW_COUNT * COLUMN_COUNT * 2
MAX_TURNS = 42
TRAIN_EPISODES = 10
GAMMA = 0.95
LEARNING_RATE = 0.001

MEMORY_SIZE = 512
BATCH_SIZE = 32

EXPLORATION_MAX = 1.0
EXPLORATION_MIN = 0.0
EXPLORATION_DECAY = 0.995